import { StyleSheet } from "react-native";

// Theme colors - converted from HSL to hex for better compatibility
export const colors = {
  primary: "#33b370",
  primaryForeground: "#ffffff",
  secondary: "#f0c030",
  secondaryForeground: "#5c4a12",
  destructive: "#dc4040",
  destructiveForeground: "#ffffff",
  success: "#33b370",
  successForeground: "#ffffff",
  warning: "#f0c030",
  warningForeground: "#5c4a12",
  background: "#f7faf8",
  foreground: "#1b332a",
  card: "#ffffff",
  cardForeground: "#1b332a",
  muted: "#e8ede9",
  mutedForeground: "#5a7366",
  border: "#dce3dd",
  input: "#dce3dd",
  ring: "#33b370",
  accent: "#4aa6e0",
  accentForeground: "#ffffff",
};

// Common styles helper
export const tw = StyleSheet.create({
  // Flex utilities
  flex1: { flex: 1 },
  flexRow: { flexDirection: "row" },
  flexCol: { flexDirection: "column" },
  flexWrap: { flexWrap: "wrap" },
  itemsCenter: { alignItems: "center" },
  itemsStart: { alignItems: "flex-start" },
  itemsEnd: { alignItems: "flex-end" },
  justifyCenter: { justifyContent: "center" },
  justifyBetween: { justifyContent: "space-between" },
  justifyStart: { justifyContent: "flex-start" },
  justifyEnd: { justifyContent: "flex-end" },

  // Text
  textXs: { fontSize: 12 },
  textSm: { fontSize: 14 },
  textBase: { fontSize: 16 },
  textLg: { fontSize: 18 },
  textXl: { fontSize: 20 },
  text2xl: { fontSize: 24 },
  text3xl: { fontSize: 30 },
  text4xl: { fontSize: 36 },
  fontNormal: { fontWeight: "normal" },
  fontMedium: { fontWeight: "500" },
  fontSemibold: { fontWeight: "600" },
  fontBold: { fontWeight: "bold" },
  textCenter: { textAlign: "center" },

  // Spacing
  p2: { padding: 8 },
  p4: { padding: 16 },
  p6: { padding: 24 },
  p8: { padding: 32 },
  px2: { paddingHorizontal: 8 },
  px4: { paddingHorizontal: 16 },
  px6: { paddingHorizontal: 24 },
  px8: { paddingHorizontal: 32 },
  py2: { paddingVertical: 8 },
  py3: { paddingVertical: 12 },
  py4: { paddingVertical: 16 },
  py6: { paddingVertical: 24 },
  m2: { margin: 8 },
  m4: { margin: 16 },
  mb1: { marginBottom: 4 },
  mb2: { marginBottom: 8 },
  mb4: { marginBottom: 16 },
  mb6: { marginBottom: 24 },
  mb8: { marginBottom: 32 },
  mt2: { marginTop: 8 },
  mt4: { marginTop: 16 },
  mt6: { marginTop: 24 },
  ml2: { marginLeft: 8 },
  ml4: { marginLeft: 16 },
  mr2: { marginRight: 8 },
  mr4: { marginRight: 16 },
  gap1: { gap: 4 },
  gap2: { gap: 8 },
  gap3: { gap: 12 },
  gap4: { gap: 16 },

  // Sizing
  w10: { width: 40 },
  w16: { width: 64 },
  w24: { width: 96 },
  w32: { width: 128 },
  w40: { width: 160 },
  wFull: { width: "100%" },
  h2: { height: 8 },
  h10: { height: 40 },
  h16: { height: 64 },
  h24: { height: 96 },
  h32: { height: 128 },
  h40: { height: 160 },

  // Border radius
  rounded: { borderRadius: 4 },
  roundedLg: { borderRadius: 8 },
  roundedXl: { borderRadius: 12 },
  rounded2xl: { borderRadius: 16 },
  roundedFull: { borderRadius: 9999 },

  // Backgrounds (need to use colors directly)
  bgBackground: { backgroundColor: colors.background },
  bgCard: { backgroundColor: colors.card },
  bgPrimary: { backgroundColor: colors.primary },
  bgSecondary: { backgroundColor: colors.secondary },
  bgDestructive: { backgroundColor: colors.destructive },
  bgSuccess: { backgroundColor: colors.success },
  bgMuted: { backgroundColor: colors.muted },

  // Text colors
  textForeground: { color: colors.foreground },
  textPrimary: { color: colors.primary },
  textMuted: { color: colors.mutedForeground },
  textDestructive: { color: colors.destructive },
  textSuccess: { color: colors.success },
  textWhite: { color: "#ffffff" },
  textPrimaryForeground: { color: colors.primaryForeground },
  textDestructiveForeground: { color: colors.destructiveForeground },
  textSuccessForeground: { color: colors.successForeground },

  // Borders
  border2: { borderWidth: 2 },
  borderBorder: { borderColor: colors.border },
  borderPrimary: { borderColor: colors.primary },
  borderSuccess: { borderColor: colors.success },
  borderDestructive: { borderColor: colors.destructive },
});

export default tw;
